version: '3.8'
services:

  
  nalog_app:
    container_name: nalog_app
    build:
      context: .
      dockerfile: ./nalog/Dockerfile
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/

  gateway:
    container_name: gateway
    build: ./nginx/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media/

volumes:
  pg_data:
  static:
  media: